apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-app
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-app
  template:
    metadata:
      labels:
        app: user-app
    spec:
      nodeSelector:
        node-role: worker
      containers:
        - name: user-app
          image: dktlfem/ci-cd-test:user-app-12-5d7d693
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: user-app-config
            - secretRef:
                name: user-app-secret
          readinessProbe:
            httpGet:
              path: /actuator/health/ping
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 6
          livenessProbe:
            httpGet:
              path: /actuator/health/ping
              port: 8080
            initialDelaySeconds: 40
            periodSeconds: 20
            timeoutSeconds: 3
            failureThreshold: 6
          resources:
            requests:
              cpu: "250m"
              memory: "512Mi"
            limits:
              cpu: "500m"
              memory: "1Gi"